"""empty message

Revision ID: 6924cf7b966b
Revises: 40f8af84ecb8
Create Date: 2023-12-13 19:59:42.560319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6924cf7b966b'
down_revision: Union[str, None] = '40f8af84ecb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baskets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Closed', 'Cancelled', name='basket_status'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baskets_id'), 'baskets', ['id'], unique=False)
    op.create_table('basket_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_basket_lines_id'), 'basket_lines', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('basket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.DECIMAL(), nullable=True),
    sa.Column('shipping_price', sa.DECIMAL(), nullable=True),
    sa.Column('shipping_method', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'Paid', 'Sent', 'Received', 'Cancelled', 'Returned', name='order_status'), nullable=True),
    sa.Column('additional_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now', nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['user_addresses.id'], ),
    sa.ForeignKeyConstraint(['basket_id'], ['baskets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_id'), 'order_lines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_lines_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_basket_lines_id'), table_name='basket_lines')
    op.drop_table('basket_lines')
    op.drop_index(op.f('ix_baskets_id'), table_name='baskets')
    op.drop_table('baskets')
    # ### end Alembic commands ###
