"""upgrade model

Revision ID: 072fb8b14730
Revises: 7143a61fcf32
Create Date: 2023-12-25 17:45:53.162046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '072fb8b14730'
down_revision: Union[str, None] = '7143a61fcf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('additionalproducts_additional_id_fkey', 'additionalproducts', type_='foreignkey')
    op.drop_constraint('recommendedproducts_recommended_id_fkey', 'recommendedproducts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('recommendedproducts_recommended_id_fkey', 'recommendedproducts', 'products', ['recommended_id'], ['id'])
    op.create_foreign_key('additionalproducts_additional_id_fkey', 'additionalproducts', 'products', ['additional_id'], ['id'])
    # ### end Alembic commands ###
