"""returned

Revision ID: 39b3777f8102
Revises: 072fb8b14730
Create Date: 2023-12-25 17:52:26.161363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39b3777f8102'
down_revision: Union[str, None] = '072fb8b14730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'additionalproducts', 'products', ['additional_id'], ['id'])
    op.create_foreign_key(None, 'recommendedproducts', 'products', ['recommended_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendedproducts', type_='foreignkey')
    op.drop_constraint(None, 'additionalproducts', type_='foreignkey')
    # ### end Alembic commands ###
