"""empty message

Revision ID: fbd38ab85616
Revises: 799909f2b79d
Create Date: 2023-12-27 18:59:41.035587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fbd38ab85616'
down_revision: Union[str, None] = '799909f2b79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additionalproducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('additional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['additional_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendedproducts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommended_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommended_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('recommendedproducts')
    op.drop_table('additionalproducts')
    # ### end Alembic commands ###
